### ISSUE TITLE
set up routes and basic actions

### ISSUE THREAD

**Issue by alubling** [alubling/maskstore#3]
Let's make a list here:
- getting all the masks (done)
- getting one mask (done)
- creating a new order
- posting a mask to an order
- posting a review
- getting a review
- getting an order (if authenticated, but this happens on the front end)
- deleting a mask from an order

**Comment by pete-ryu** [comment]
Revision:
- getting all the masks (done)
- getting one mask (done)
- creating a new order
- posting a review
- getting review
- getting all past orders for user

**Comment by bfrost12** [comment]
Finished all the routes. Here's the final list. Submitting a pull request. 

Masks:
-Get all masks
-Get one mask by mask id
-Create a new mask 
-Update a mask by mask id
-Delete a mask by mask id

Users:
-Get all users
-Get one user by user id
-Create a new user
-Update a user by user id
-Delete a user by user id

Orders:
-Get all orders
-Get one order by order id
-Get all orders for a single user by user id
-Create a new order
-Update an order by order id
-Delete an order by order id

Reviews:
-Get all reviews
-Get one review by review id
-Get all reviews for a single mask by mask id
-Get all reviews for a single user by user id
-Create a new review
-Update a review by review id
-Delete a review by review id
